### ISSUE TITLE
Ability to disable a rule for selected cluster - backend part

### ISSUE THREAD

**Issue by Bee-lee** [RedHatInsights/insights-results-aggregator#302]
UI part: #169 

The user wants to disable rules that they're not interested in for a specific cluster in order to hide them from the report. 

Therefore, the user should also have the ability to:
- see the rules that have been disabled (+possibly see when that happened)
- re-enable them (+possibly see when that happened)

## Tasks:
- [ ] create storage part for cluster+organization+rule
    - schema should include date of disablement and possibly date of re-enablement

- [ ] create endpoints for disabling and enabling rules per cluster and organization.
    - allow multiple rules at once, so the user would be able to possibly disable a filtered selection of rules

- [ ] decide on the method of serving the rules, depending on UI decision, and implement it. see below. I'll update it later.

### Possible implementations of serving the disabled rules

1) API endpoint for report `report/{organization}/{cluster}` always returns all rules - separated into two lists of hit rules (as present) and disabled rules. 
    - this would be better if the disabled rules were in the same tab/component, without having to reload it. if the request for disable/enable would return an error, frontend would handle it with a callback.
2) API endpoint for report returns only enabled rules. Disabled rules are served as a separate endpoint, probably `clusters/{cluster}/rules`
    - this would be better if the disabled rules were in a different tab/component than the normal rules/report which would require a tab/table switch anyway
